### ISSUE TITLE
Some notes

### ISSUE THREAD

**Issue by DamienCassou** [nixcloud/tour_of_nix#1]
- in https://nixcloud.io/tour/?id=23, the text says `fix ex13, what is the problem?` but there is no ex13
- in the same exercise, an explanation is missing about `isString (x:x)`

**Comment by qknight** [comment]
see: https://nixcloud.io/tour/?id=22 where it is fixed:

solution:
**(x:x) is a special form of: (http://foo.com), that is: a = http://foo.com with precedence parentheses!**

thanks for pointing that out. hope you enjoyed the tour.
