### ISSUE TITLE
Give a little bit of syntax in "31 / 32 - Reimplementation: catAttrs"

### ISSUE THREAD

**Issue by DamienCassou** [nixcloud/tour_of_nix#2]
Hi,

in `id=31`, could you please add a small sentence saying that the right-hand side of the`?` operator has the same syntax as the assignment in attrsets (i.e., `{foo=42;}` and `{"foo" = 42;}` are equivalent)? In the sense that the `${variable}` syntax is necessary.

**Comment by qknight** [comment]
done & thanks for the feedback.
