### ISSUE TITLE
Some issues I discovered while doing a tour of nix

### ISSUE THREAD

**Issue by Janik-Haag** [nixcloud/tour_of_nix#21]
Question 18 doesn't have ex06 https://nixcloud.io/tour/?id=18 which the evaluation asks for

**Comment by qknight** [comment]
i had moved the '?' operator question to a later place. thanks for making the tour better! just forgot to fix the solution. should have done test driven development ;-)

thanks for pointing this out!

**Comment by Janik-Haag** [comment]
Thank you for making this it helped me get some deeper understanding of the nix language after using nixos for almost a year now and maintaining ~50+ packages and a few modules. Btw not really related but maybe add a link to noogle.dev/ in further resources

**Comment by qknight** [comment]
Nice to hear that. I've added the noogle.dev at https://nixcloud.io/tour/?id=5 thanks for pointing this out!
