### ISSUE TITLE
Strange nix warning

### ISSUE THREAD

**Issue by danbst** [nixcloud/tour_of_nix#8]
I've done a typo to one of exercises:

```
let
  min = a: b: a;
  min = a: b: b;
in
{
  ex1 = min 5 3;
  ex2 = max 9 4;
}
```

The resulting error:

```
error: undefined variable ‘min’ at line:6:9
```

Strange, huh? Nix 1.11.2 gives

```
# nix-instantiate --eval -E "(import ./test.nix).ex1"
error: attribute "min" at /root/test.nix:3:3 already defined at /root/test.nix:2:3
```

**Comment by qknight** [comment]
well, we don't do 1.11.2 but a older version, hence the message.

**Comment by danbst** [comment]
As far as I understand, it is hard to update bundled Nix. A pity. But clear warning messages are IMO crucial for learning process. (Disclaimer: I've already learned Nix and most of it's quirks)

**Comment by qknight** [comment]
you are right, but that is actually the error nix returns. we didn't change anything.

**Comment by qknight** [comment]
On nixcon23 I've meet Thomas Bereknyei and he got the most recent version of nix working using emscription. When this has been released, I'll integrate this into the tour!
