### ISSUE TITLE
Comments on exercises 6 and 8

### ISSUE THREAD

**Issue by danbst** [nixcloud/tour_of_nix#9]
## Ex 6 Functions: Introduction

Missing note about function arguments. Also I think it is better to notice, that there must be at least 1 space between arguments. Otherwise strange errors start occurring.
## Ex 8 Functions: your part...

> Note: those functions already exist and can be accessed with lib.min and lib.max **(don't do this in this exercise)**

Later...

> Now, instead of calling your min and max implementation, use lib.min and lib.max.

Maybe remove the "don't do this" part? I was thinking that whole page is an exercise.

**Comment by eliasp** [comment]
I agree. Up to this point one has no clue how functions are built from a syntactic PoV - there should be either a reference to https://nixos.org/nix/manual/#ss-functions or an example…

**Comment by qknight** [comment]
I've added these two links then:

**Note:** Read about writing functions in <https://nixos.org/manual/nix/stable/language/constructs#functions>\n\n**Note:** There are builtin functions you can always use, see <https://nixos.org/manual/nix/stable/language/builtins>
